trigger:
  - main
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: Use Dotnet 9
    inputs:
      version: "9.0.x"

  - script: dotnet clean
    displayName: "dotnet clean"

  - script: dotnet publish -p:PublishProfile=PublishProfile -p:Password=4hSRfWvJ4upkC66wguRRMsWDydqhJxoaYa32p3iaWah2e7khw6Ep2YFBisoK
    displayName: "dotnet publish"